### ISSUE TITLE
Magpie Tx

### ISSUE THREAD

**Issue by Valdorff** [Valdorff/rp-thoughts#19]

**Comment by Valdorff** [comment]
Figure out how to do a Magpie Tx. make one showing work, submit on Safe

**Comment by xrchz** [comment]
What are we talking about here? At a guess, would it be doing what "Add Bribe" does on the rETH pool on this website? https://www.pendle.magpiexyz.io/bribe Which network - seems like there's Arbitrum and Optimism as options? And which reward token? RPL is not listed as an option there.
